run 3d test

diff --git a/.github/workflows/test_checks.yml b/.github/workflows/test_checks.yml
--- a/.github/workflows/test_checks.yml
+++ b/.github/workflows/test_checks.yml
@@ -32,7 +32,21 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
+      - uses: chickensoft-games/setup-godot@v1
+        name: 🤖 Setup Godot
+        with:
+          version: 4.3.0
+          use-dotnet: false
+          include-templates: true
       - name: Run Tests for 3D Build
         shell: sh
         run: |
           cargo test --all-targets --features="build3d,test" --no-default-features
+          ./scripts/build-dev-3d.sh
+          godot --headless --path ./bin3d test.tscn --quit-after 1000 > output.log 2>&1
+          if grep -q "ERROR:" output.log; then
+            echo "Error found in output"
+            exit 1
+          else
+            echo "No errors found"
+          fi
